### ISSUE TITLE
Save a menu

### ISSUE THREAD

**Issue by kensanata** [solderpunk/VF-1#31]
Sometimes I want to save a menu, or a search result, not a text file. Menus don't get a `self.tmp_filename` in `_handle_index` and thus cannot be saved, though. This would make visiting text files even more interesting.

**Comment by solderpunk** [comment]
Hmm, valid point.

It's starting to feel inevitable that menus end up getting saved to textfiles as well.  This would trivially solve everybody's complaints about not being able to `less` long menus, in addition to letting you save them.

**Comment by kensanata** [comment]
Hm, not sure. You still won’t be able to page a menu and use it at the same time. You’ll page through the raw menu, right?

**Comment by solderpunk** [comment]
Yeah, true, you would need to remember the index number you wanted, `q` out of `less` and then enter that number as a separate command.

**Comment by kensanata** [comment]
I think what I really want is this: run a Veronica search or something similar, and then I want to be able to `save` and `add` and `mark` the search result without having to rerun the search itself. It seems to me that `save x` followed by `go x` might do just that (because VF-1 does visit local files as menus).

**Comment by solderpunk** [comment]
Oh, that's really great!

**Comment by kensanata** [comment]
As for paging through a menu: `! sed -e 's/^.//;s/\t.*//;' | less` does it for me? No fancy item type indicators, of course. But good enough to admire ASCII art. :)

**Comment by kensanata** [comment]
Now I'm wondering whether there should be an `alias` command. Then we could put the following into our config file:
```
alias page-menu="! sed -e 's/^.//;s/\t.*//;' | less"
```

**Comment by solderpunk** [comment]
As of last night, `less` should just work on menus.  I'm now saving the rendered menus to a separate tempfile.  The "raw" menu is still used for `save`, though, so your method of caching search results should still work.

**Comment by kensanata** [comment]
Excellent.
