### ISSUE TITLE
Maybe we should build in more search options than Veronica?

### ISSUE THREAD

**Issue by solderpunk** [solderpunk/VF-1#41]
We currently allow searching Veronica 2 very quickly and easy with the `(v)eronica` command.

I've wondered about maybe adding a `gopherpedia` command for searching Gopherpedia, as this could be handy, too.  Similarly, once the Project Gutenberg mirror is working nicely, that would be a candidate, too.

Obviously, this could get out of hand, with lots and lots of single use search commands.  But I feel like very large, well-known and stable Gopher search services of broad interest (like the above) are maybe something we should consider directly supporting.

Thoughts?

**Comment by kensanata** [comment]
My thoughts are "yes". I see two implementations:

1. have a setting with the default search engine and one command to use it.
2. or have a two word command like `search veronica foo`

**Comment by solderpunk** [comment]
Option 1. feels too clunky to me, if I have to change the default search engine each time I want to search somewhere else, it's not much less effort to just keep the search engine as a bookmark and navigate to it.

Option 2 seems nice enough - at this point I kind of regret having named the existing `search` command `search`.  We're still 0.0.x, so not technically bound to backward compatibiilty, so this *could* change.  It might not even be much of a pain point for users, ever since you introduced the `/` shortcut I have never once actually typed `search` or even `se`...

In terms of usability, nothing beats adding a `gopherpedia` command, I just worry about setting the precedent, in case gopher ever picks up many more search providers some day...

**Comment by kensanata** [comment]
It would be interesting to learn how people use the tools. I never type search, but I also never use Veronica. I do search my own site using the two options I have (full text search and page matching). I don’t know what that means. Perhaps I’m the kind of person that would simply bookmark the pages of the search engines?

**Comment by solderpunk** [comment]
I see that back in 2018 I thought the idea of an option to change the URL used by a generic `search` command felt clunky!  But since then I ended up implementing exactly that approach in AV-98, and it seems silly at this point to use it in one client but not the other, so I've gone ahead and done that.

The old `search` command is now `filter`.  I will solicit feedback on this, but I strongly suspect nobody will even notice the change.
