### ISSUE TITLE
Missing tags in git

### ISSUE THREAD

**Issue by vext01** [solderpunk/VF-1#51]
Hi,

First, thanks for vf1. Very nice.

A few months back I imported vf1 into OpenBSD ports at the request of a user. The version we imported was 0.0.10. I came here today to see if there is a newer version, but I notice that 0.0.10 isn't actually tagged in git.

I see that I can look up releases on PyPI, but it might also be good to tag releases in git?

Thanks

**Comment by solderpunk** [comment]
Hi there,

Sorry about this!  I had actually tagged the 0.0.10 release (and other seemingly missing releases), I just hadn't pushed the tags to the GitHub repo.  They're all there now, and I'll try to be more mindful of this in future (a new release should happen soon).  Thanks for bringing this to my attention!
