### ISSUE TITLE
Make sure VF-1 prompt starts at leftmost column

### ISSUE THREAD

**Issue by kseistrup** [solderpunk/VF-1#52]
If the current document doesn't end with a line terminator, VF-1's prompt will be displaced. An actual example can be seen at

```
  gopher://txtn.ws/0/zAbout.txt
```

VF-1 should check if the current document ends with a line terminator, and add one if if doesn't.

**Comment by solderpunk** [comment]
Thanks @kseistrup for the report and @pacoesteban for the fix!  Sorry for the delayed response.
