### ISSUE TITLE
Allow automatic activation of TLS

### ISSUE THREAD

**Issue by solderpunk** [solderpunk/VF-1#54]
@kensanata Our current implementation of TLS follows a very strict "no surprises" policy, where it's impossible to visit an encrypted gopherhole while TLS is off and impossible to visit an unencrypted gopherhole while TLS is on.  The user needs to exercise full manual control and therefore always knows what situation there in.

How do you feel about automatically switching TLS on if a user tries to `go` to a `gophers://` URL?  By using the `gophers://` scheme, the user is arguably explicitly asking for encryption to be used.  Even if they are not paying attention, being surprised by accidentally using encryption is not really a bad surprise - not at all like being surprised by accidentally *not* using encryption, which I agree we should always avoid.

Right now I *think* this is a good idea, but I'm not 100% sure and would welcome another opinion/perspective.

**Comment by kensanata** [comment]
This sounds like a good idea. Plus a little message saying we switched into TLS mode.

**Comment by solderpunk** [comment]
Yes, certainly with a message making it clear what is happening.

Another thought: currently all `GopherItem`s constructed from menu lines have their `tls` attribute set to match the client's current `tls` attribute.  This means that if a user visits an encrypted gopher server, all links to other servers will be interpreted as being encrypted too.  This will be false 99.99% of the time, resulting in a slow timeout and then the user having to toggle TLS off.  Does it make more sense to construct `GopherItem`s whose host and port match that which served the menu based on the client's current TLS setting, and set all outbound links to non-TLS?  Then when a user tries to leave they immediately get a "Need to turn off TLS to leave the secure server!" error, instead of an eventual timeout.

**Comment by kensanata** [comment]
Personally, I’m still hoping that one day we will have a new, separate, always secure gophers network to us and then we will get warnings when we leave it to back to ol‘ insecure gopher. In light of this vision, I think that we should not default to insecure outbound link following. Perhaps we could add a heuristic based on port: if and only if the outbound link goes to port 7, either visually indicate that the link is probably insecure before the user follows it, and/or warn the user before proceeding.

Alternatively, is there a way to just read the first n bytes to determine a TLS handshake? If so, we can always test before trying to read a secured line? Much trickier, of course.

Or, as a stop gap measure: keep the current model but remember every host/port combo and whether we last accessed it using TLS or not. If the host/port is in the cache, no more timeouts.
