### ISSUE TITLE
Initialization and the RC file

### ISSUE THREAD

**Issue by kensanata** [solderpunk/VF-1#61]
I have built [mdcat](https://github.com/lunaryorn/mdcat) on my system, and created an RC file:
```
echo "handler text/plain mdcat %s" >> ~/.config/.vf1rc
```

When I visit an URL from the command line, it seems to have no effect:
```
$ vf1 gopher://alexschroeder.ch:70/0Comments_on_2019-06-12_What_I_want_from_Gopher
```
The output looks like plain text.

Using the `go` command works, however:
```
$ vf1
VF-1> go gopher://alexschroeder.ch:70/0Comments_on_2019-06-12_What_I_want_from_Gopher
```

It is not necessary to build `mdcat` to reproduce the problem. Simply replacing `mdcat` with `wc` in the RC file is enough.

**Comment by solderpunk** [comment]
Nice catch!  I can see how to fix this, shouldn't take long...

**Comment by solderpunk** [comment]
Should be fixed now, could you test and confirm?

**Comment by kensanata** [comment]
Works for me, thanks!
