### ISSUE TITLE
Splitting on whitespace in do_links

### ISSUE THREAD

**Issue by kensanata** [solderpunk/VF-1#64]
Strange problem because I want to put an URL at the end of a sentence, like this:

```
... protect your browsing via TLS and using
gophers://alexschroeder.ch:7443.
```

When I use the `links` command, the period is considered to be part of the port and parsing breaks:

```
ValueError: invalid literal for int() with base 10: '7443.'
```

OK, reading up on Python's str split sep arg:

> None (the default value) means split according to any whitespace

So I'll add a ZERO WIDTH SPACE between the port and the period...

But no:

```
ValueError: invalid literal for int() with base 10: '7443\u200b.'
```

So, what now?

1. we could make VF-1 fancier, and strip trailing punctuation in some situations (ugh)
2. we could provide our own interpretation of what whitespace assuming the text is UTF-8 (meh)
3. we could just catch such URL parsing errors and add an info line to the `links` menu saying that we couldn't parse the URL even though it looks like an URL (hm…)

What do you think? Other than "don't do that, then!" which is of course a valid point of view.

**Comment by kensanata** [comment]
I also remember the W3C recommendation using angled brackets [wrappers for URLs in plain text](https://www.w3.org/Addressing/URL/5.1_Wrappers.html), and since angled brackets aren't whitespace, this won't work.

Basically I guess what I'm saying is that we should scan the text with an URL-matching regular expression, I think?

**Comment by kensanata** [comment]
I don't like [https://stackoverflow.com/questions/9760588/how-do-you-extract-a-url-from-a-string-using-python/42255191#42255191 urlextract] because it updates the top level domains, apparently.

For my wiki written in Perl I've used the following:

```perl
  $UrlProtocols = 'http|https|ftp|afs|news|nntp|mid|cid|mailto|wais|prospero|telnet|gopher|irc|feed';
  $UrlProtocols .= '|file' if $NetworkFile;
  my $UrlChars = '[-a-zA-Z0-9/@=+$_~*.,;:?!\'"()&#%]'; # see RFC 2396
  my $EndChars = '[-a-zA-Z0-9/@=+$_~*]'; # no punctuation at the end of the url.
  $UrlPattern = "((?:$UrlProtocols):$UrlChars+$EndChars)";
  $FullUrlPattern="((?:$UrlProtocols):$UrlChars+)"; # when used in square brackets
```

`$UrlPattern` tries to exclude trailing punctuation; `$FullUrlPattern` is strict.

And for my own site, I've added gophers, of course! :)

**Comment by solderpunk** [comment]
I have an arguably irrational fear of using regexes in situations where standard Python code can do the same thing, even if it's slower.  This is because the Python equivalent tends to be much, much easier to read and maintain than arcane regex strings.  I added some code a week ago which makes VF-1 a little smarter about link extraction.  Could you please confirm whether your use case now works fine?

**Comment by kensanata** [comment]
Sadly I'm on a trip and don't get much laptop time for the next two weeks...

**Comment by solderpunk** [comment]
I created a test file of my own just now which contains a URL ending with a dot.  The `links` command seems to extract it without any problems.  So I guess the code I referenced in my last commend above did indeed fix things, and therefore I'm closing this issue.
