### ISSUE TITLE
add a option to see the 'vf-1' version

### ISSUE THREAD

**Issue by cremesk** [solderpunk/VF-1#68]
I have just looked at vf-1 and find it very well done! One thing I noticed is that can we add please an option to display the vf-1 version? Like: ‘vf1 -v’

Thanks
~creme

**Comment by solderpunk** [comment]
Thanks for the suggestion!  You can now use `vf1 --version` to get the installed version from the shell, or use the `version` command from within VF-1 itself.

Look forward to the same in AV-98 shortly!
